# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('dining_hall', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to=b'')),
                ('price_type', models.CharField(choices=[('S', 'Standard'), ('E', 'Ecomomy'), ('EH', 'Enhanced')], default='S', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='3', max_length=1)),
                ('review', models.CharField(max_length=10000, null=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nu_dorm_ratings_app.Dorm')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('major', models.CharField(max_length=100, null=True)),
                ('wants_roommate', models.BooleanField(default=False)),
                ('sleep_habits', models.CharField(choices=[('M', 'Morning Person'), ('N', 'Night Person'), ('F', 'Flexible')], default='F', max_length=1)),
                ('description', models.CharField(max_length=255, null=True)),
                ('cleanliness', models.CharField(choices=[('A', 'Average'), ('N', 'Neat'), ('M', 'Messy')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nu_dorm_ratings_app.User'),
        ),
    ]
