# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nu_dorm_ratings_app', '0002_auto_20180813_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='price_type',
            field=models.CharField(choices=[('S', 'Standard'), ('E', 'Economy'), ('EH', 'Enhanced')], default='S', max_length=2),
        ),
    ]
