# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nu_dorm_ratings_app', '0003_auto_20180814_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='price_type',
            field=models.CharField(choices=[('S', 'Standard'), ('E', 'Ecomomy'), ('EH', 'Enhanced')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
